version: "3.8"
services:
  mongodb:
    image: mongo
    container-name: mongodb-server
    ports:
      - 27017:27017
    environment:
      - MONGO_INIT_ROOT_USERNAME=user
      - MONGO_INIT_ROOT_PASSWORD=RooTpass

  mongo-express:
    image: mongo-express
    container-name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=RooTpass
      - ME_CONFIG_MONGODB_SERVER=mongodb

  networks:
    default:
      name: mongodb-network